#!/bin/csh
#
setenv CC gcc
setenv F77 gfortran
setenv FC gfortran

./configure --prefix=/home/globc/page/codes/local --with-debugging=4 --with-zlib=/data/local64 --with-szlib=/data/local64 --with-hdf5=/data/local64 --with-netcdf=/data/local64 --with-udunits=/data/local64/udunits2

